name: Database Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select database action'
        required: true
        default: 'reset'
        options:
          - create
          - drop
          - migrate
          - seed
          - reset

jobs:
  manage-database:
    runs-on: ubuntu-latest

    env:  # Set environment variables at the job level
      NODE_ENV: production
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create Database
        if: ${{ github.event.inputs.action == 'create' }}
        run: npx sequelize-cli db:create

      - name: Drop Database
        if: ${{ github.event.inputs.action == 'drop' }}
        run: npx sequelize-cli db:drop

      - name: Migrate Database
        if: ${{ github.event.inputs.action == 'migrate' }}
        run: npx sequelize-cli db:migrate

      - name: Seed Database
        if: ${{ github.event.inputs.action == 'seed' }}
        run: npx sequelize-cli db:seed:all

      - name: Reset Database
        if: ${{ github.event.inputs.action == 'reset' }}
        run: |
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate